#!/usr/bin/env python

import argparse
from scipy.misc import imread, imsave
from cv2.ximgproc import guidedFilter
from guided_filter.core.filters import FastGuidedFilter

parser = argparse.ArgumentParser(description="De-rain an image")
parser.add_argument(
    'input',
    metavar='I',
    help="An image to de-rain",
)
parser.add_argument(
    'output',
    metavar='O',
    help="De-rained image output file name",
    nargs="?",
    default="out.jpg",
)

args = parser.parse_args()

img = imread(args.input)

gf = FastGuidedFilter(img,16,2,4)
img_base = gf.filter(img)
img_detail = img / 255.0 - img_base

img_combine = img_base + img_detail

imsave(args.output, img_base)
imsave("detail.jpg", img_detail)
imsave("combine.jpg", img_combine)
