#!/usr/bin/env python

import argparse
import img
from scipy.misc import imread, imsave
from cv2.ximgproc import guidedFilter
from guided_filter.core.filters import FastGuidedFilter

parser = argparse.ArgumentParser(description="De-rain an image")
parser.add_argument(
    'input',
    metavar='I',
    help="An image to de-rain",
)
parser.add_argument(
    '-o', '--output',
    help="De-rained image output file name",
    nargs="?",
    default="out.jpg",
)

args = parser.parse_args()

img_base, img_detail = img.split(imread(args.input))

img_combine = img_base + img_detail

imsave(args.output, img_base)
imsave("detail.jpg", img_detail)
imsave("combine.jpg", img_combine)
