#!/usr/bin/env python

from tqdm import tqdm

from argparse import ArgumentParser, ArgumentTypeError
from pathlib import Path
import img
from scipy.misc import imread
import numpy as np
import processor

p = ArgumentParser(description="Train the neural network.")
p.add_argument(
    "dir",
    type=str,
    help="directory containing the training files",
)
p.add_argument(
    "--truth-subdir",
    default="ground truth",
    type=str,
    help="subdirectory of training directory containing ground truth files",
)
p.add_argument(
    "--input-subdir",
    default="rainy image",
    type=str,
    help="subdirectory of training directory containing training input files",
)
p.add_argument(
    "--ext",
    default=".jpg",
    type=str,
    help="truth and input file extensions",
)

if __name__ == "__main__":
    a = p.parse_args()

    paths = {
        t: Path(a.dir, a.input_subdir).glob(t.stem + "_[0-9]*" + a.ext)
        for t in Path(a.dir, a.truth_subdir).iterdir()
        if t.suffix == a.ext
    }

    cnn_processor = processor.Convolver(
        # layer 1: 512 kernels of 16 x 16 x 3
        np.array([np.zeros((16,16,3)) for _ in xrange(512)]),
        # layer 2: 512 kernels of 1 x 1 x 512
        np.array([np.zeros((1,1,512)) for _ in xrange(512)]),
        # layer 3: 3 kernels of 8 x 8 x 512
        np.array([np.zeros((8,8,512)) for _ in xrange(3)]),
    )

    for p_truth, ps_input in tqdm(
            paths.iteritems(),
            desc="Progress",
            total= len(list(Path(a.dir, a.input_subdir).glob("*"+a.ext))),
    ):
        _, i_truth = img.split(imread(p_truth))
        for p_input in ps_input:
            _, i_input = img.split(imread(p_input))
            cnn_processor.process(i_input)
            # TODO: training wizardry
