#!/usr/bin/env python

from tqdm import tqdm

from argparse import ArgumentParser
from pathlib import Path
import img
from scipy.misc import imread

p = ArgumentParser(description="Train the neural network.")
p.add_argument(
    "dir",
    type=str,
    help="directory containing the training files",
)
p.add_argument(
    "--truth-subdir",
    default="ground truth",
    type=str,
    help="subdirectory of training directory containing ground truth files",
)
p.add_argument(
    "--input-subdir",
    default="rainy image",
    type=str,
    help="subdirectory of training directory containing training input files",
)
p.add_argument(
    "--ext",
    default=".jpg",
    type=str,
    help="truth and input file extensions",
)

if __name__ == "__main__":
    a = p.parse_args()

    paths = {
        t: Path(a.dir, a.input_subdir).glob(t.stem + "_[0-9]*" + a.ext)
        for t in Path(a.dir, a.truth_subdir).iterdir()
        if t.suffix == a.ext
    }

    for p_truth, ps_input in tqdm(
            paths.iteritems(),
            desc="Progress",
            total= len(list(Path(a.dir, a.input_subdir).glob("*"+a.ext))),
    ):
        _, i_truth = img.split(imread(p_truth))
        for p_input in ps_input:
            _, i_input = img.split(imread(p_input))
            # TODO: training wizardry
